theme: jekyll-theme-architect
title: Dani G
logo: "/images/Grow&TechnologyHeadshots-24.jpg?raw=true"
description: >
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/danimcgee/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-91951644-1
